language: generic
sudo: required

services: 
  - docker


before_install: 
  - docker build -t vlad1pintea/docker-react -f Dockerfile.dev .  

script: 
  - docker run -e CI=true vlad1pintea/docker-react npm run test -- --coverage